[project]
name = "flying-to-the-moon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dynaconf>=3.2.11",
    "flask>=3.1.2",
    "rethinkdb>=2.4.10.post1",
    "waitress>=3.0.2",
]
